version: 2

models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
                error_if: ">1000"
                warn_if: ">10"

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
                error_if: ">1000"
                warn_if: ">10"
          - not_null:
              
      - name: apply_kind
        tests:
          - accepted_values:
              values: ['I', 'U']
